### PR TITLE
Update R in Travis 

### PR DESCRIPTION
**Pull request by parismita**
#33

### CODE REVIEW

**Comment by parismita** [comment]
I used this link as example to switch to R-3.5, as the one used is deprecated

https://eddelbuettel.github.io/r-travis/
https://github.com/eddelbuettel/rcppannoy/blob/master/.travis.yml

**Comment by parismita** [comment]
@aldro61  I updated the r-travis, Can you check if I included any non-required package

**Review by tdhock — APPROVED** [review]
looks reasonable to me

**Comment by aldro61** [comment]
That looks good! Merging.

**Pull request merged**
